# version: uri
---
1.7.1_1:
    uri: https://iwm.dhe.ibm.com/sdfdl/1v2/regs2/linuxjavasdks/java/java7v1/7.1.2.0/linuxamd64/Xa.2/Xb.Xv-w_qjvCAyMmKG9a2VfXnbI55SNmqO62IWIiJGbGQ/Xc.7.1.2.0/linuxamd64/ibm-java-x86_64-sdk-7.1-2.0.bin/Xd./Xf.LPr.D1vk/Xg.7821547/Xi.swg-sdk7v1/XY.regsrvs/XZ.1YWAPb8IB-xf8hx6RjhtcDYsj6k/ibm-java-x86_64-sdk-7.1-2.0.bin
    license: https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?la_formnum=&li_formnum=L-AWON-8GALN9&title=IBM%C2%AE+SDK%2C+Java-+Technology+Edition%2C+Version+7.0&l=en
